name: update data of youtube videos

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Run update data script
        run: YOUTUBE_TOKEN=${{ secrets.YOUTUBE_TOKEN }} node src/data/updateData.js 
        
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Your Name
          author_email: mail@example.com
          message: 'Update video details'
          add: 'src/data/videoDetails.json'
